spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://auth-db:5432/auth_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: false
    clean-disabled: false
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
  issuer: ${JWT_ISSUER:music-store}
  audience: ${JWT_AUDIENCE:music-store-api}

server:
  port: 8081
  tomcat:
    max-http-header-size: 1048576

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
